# Stage 1: Build the Angular application
FROM node:latest AS build
WORKDIR /app

COPY package*.json ./
RUN npm install -g @angular/cli@16.2.1
RUN npm install

COPY . .
RUN npm run build

# Stage 2: Serve the Angular application with Nginx
FROM nginx:latest
COPY --from=build /app/dist/ /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 4200
CMD ["nginx", "-g", "daemon off;"]
