version: "3.1"

services:
  #Our service.
  server:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: "reservation-service"
    hostname: "reservation-service"
    #Mapping ports
    ports:
      # <port_on_local>:<port_in_machine>
      - 8002:8002
    #Will be accessible through os.Getenv("PORT")
    environment:
      - PORT=8002
      # NoSQL: environment variable holding connection URI for Cassandra database
      - CASS_DB=cassandra:9042
    # NoSQL: Extremely important! Cassandra takes a lot of time to start!
    # If we don't wait for it to fully initialize we will get exceptions and will not be able to connect!
    depends_on:
      cassandra:
        condition: service_healthy

  # NoSQL: CassandraDB
  cassandra:
    image: cassandra
    restart: always
    ports:
      - "9042:9042"
    # Docker healtcheck - checks if database is "alive"
    healthcheck:
      test: ["CMD-SHELL", "cqlsh -e 'describe cluster'"]
      interval: 15s
      timeout: 5s
      retries: 15
    volumes:
      - cass_store:/var/lib/cassandra/data

volumes:
  cass_store:
