version: "3.1"

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: "accommodation-server"
    hostname: "accommodation-server"
    #OVDE MAPIRAM PORTOVE DRUGARI
    ports:
      # <port_on_local>:<port_in_machine>
      - 8080:8080
    #Will be accessible through os.Getenv("PORT")
    environment:
      - PORT=8080
      # NoSQL: environment variable holding connection URI for Mongo database
      # protocol://username:password@hostname:port
      - MONGO_DB_URI=mongodb://simikic:simikic@cluster0.kxo3ocx.mongodb.net:27017/?retryWrites=true&w=majority
    # NoSQL: Our service will try to connect to Mongo before it is up
    # in order to avoid that problem, we specify that it depends on mongo service
    # which defines the order of starting the containers
    # Additionaly we specify that mongo service needs to pass a healthcheck
    depends_on:
      mongo:
        condition: service_healthy

  # NoSQL: MongoDB
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: simikic
      MONGO_INITDB_ROOT_PASSWORD: simikic
      MONGO_INITDB_DATABASE: accommodationServiceDB
    # Docker healtcheck - checks if database is "alive"
    healthcheck:
      test: echo 'db.runCommand("ping").ok'
      interval: 10s
      timeout: 10s
      retries: 10
    volumes:
      - mongo_store:/data/db

  # NoSQL: MognoExpress
  mongo-express:
    image: mongo-express
    restart: always
    environment:
      # hostname of mongo databse
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_ADMINUSERNAME=simikic
      - ME_CONFIG_MONGODB_ADMINPASSWORD=simikic
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin
    depends_on:
      - mongo
    ports:
      - "8081:8081"
    volumes:
      - mong_express_data:/data/db

volumes:
  mongo_store:
  mong_express_data:
